name: Release Zotero/Juris-M .deb packages

on:
  schedule:
    - cron: 0 */2 * * *
  push:
  workflow_dispatch:
    inputs:
      build:
        description: forced rebuild
        type: boolean
        required: false
        default: false
      publish:
        description: forced publish
        type: boolean
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  apt:
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.rebuild.outputs.updated }}
    steps:
    - uses: actions/checkout@v6

    - name: install node
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
    - name: install node packages
      run: npm install --no-package-lock && npm ls

    - name: restore repo cache
      uses: actions/cache/restore@v5
      with:
        path: apt/
        key: zotero-repo-last-known
        restore-keys: |
          zotero-repo-

    - name: install build requirements
      run: |
        echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
        echo "::group::installing build packages"
        sudo apt-get update -q
        sudo apt-get install -y devscripts fakeroot moreutils pandoc imagemagick nfpm
        echo "::endgroup::"
        which magick || which mogrify || echo 'imagemagick not installed'
        which nfpm || echo 'nfpm not installed'

    - name: import GPG key
      uses: retorquere/ghaction-import-gpg@rebase
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: rebuild
      id: rebuild
      run: make
      env:
        BUILD: ${{ github.event.inputs.build }}
        PUBLISH: ${{ github.event.inputs.publish }}

    - name: show status
      run: echo publish=${{ steps.rebuild.outputs.updated }}

    - name: install rclone
      if: steps.rebuild.outputs.updated == 'true'
      run: curl https://rclone.org/install.sh | sudo bash

    - name: configure rclone
      if: steps.rebuild.outputs.updated == 'true'
      run: |
        mkdir -p ~/.config/rclone
        cat <<EOF > ~/.config/rclone/rclone.conf

        [b2-apt-package-archive]
        type = b2
        account = ${{ secrets.B2_APPLICATION_KEY_ID }}
        key = ${{ secrets.B2_APPLICATION_KEY }}
        hard_delete = true
        download_url = https://zotero.retorque.re
        EOF

    - name: publish repo
      if: steps.rebuild.outputs.updated == 'true'
      run: |
        rclone sync apt b2-apt-package-archive:apt-package-archive -v
        rclone cleanup b2-apt-package-archive:apt-package-archive -v

    - name: generate cache content hash
      if: steps.rebuild.outputs.updated == 'true'
      id: hash
      run: |
        echo "hash=$(sha256sum apt/*.deb | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
    - name: save cache
      if: steps.rebuild.outputs.updated == 'true'
      continue-on-error: true
      uses: actions/cache/save@v5
      with:
        path: apt/
        key: zotero-repo-${{ steps.hash.outputs.hash }}

  install:
    needs: apt
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [ 'list', 'sources' ]
    outputs:
      status: success
    steps:
    - name: allow cloudflare CDN time to settle
      if: needs.rebuild.outputs.updated == 'true'
      run: sleep 60

    - uses: actions/checkout@v6

    - name: install python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'

    - name: install apt repo
      run: |
        export INSTALLSH=https://raw.githubusercontent.com/retorquere/zotero-pkg/master/install.sh
        echo INSTALLSH=$INSTALLSH
        curl -sL $INSTALLSH | tee install.sh | sudo bash -s -- -m ${{ matrix.mode }}
        echo ==== install.sh ===
        cat install.sh
        echo ==== zotero.${{ matrix.mode }} ===
        cat /etc/apt/sources.list.d/zotero.${{ matrix.mode }}

    - name: install all the things
      run: |
        sudo apt -y clean
        sudo apt -y update
        sudo apt -y install desktop-file-utils zotero zotero-beta xvfb libegl1 libgl1 libdbus-glib-1-2

    - name: test all the things
      run: |
        pip install xvfbwrapper
        for c in zotero zotero-beta; do
          ./start.py $c
          desktop-file-validate /usr/share/applications/$c.desktop && echo 'all clear!'
        done

  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-platforms = aarch64-linux i686-linux

      - name: Setup Cachix
        uses: cachix/cachix-action@v17
        with:
          name: retorquere
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Update versions
        id: update
        run: |
          npm i
          node nix.js

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          platforms: arm64,armhf,i386

      - name: Build and Push
        if: steps.update.outputs.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add nix.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: update zotero versions" && git push)
          set -o pipefail
          nix build .#packages.x86_64-linux.zotero \
                    .#packages.x86_64-linux.zotero-beta \
                    .#packages.aarch64-linux.zotero \
                    .#packages.aarch64-linux.zotero-beta \
                    .#packages.i686-linux.zotero \
                    .#packages.i686-linux.zotero-beta \
                    --accept-flake-config --json | jq -r '.[].outputs.out' | cachix push retorquere

  test:
    needs: nix
    runs-on: ubuntu-latest
    steps:
    - run: curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm
    - run: nix profile add "github:retorquere/zotero-pkg#zotero" --accept-flake-config
    - run: zotero --version
